### PR TITLE
Simplify pretty printing code

### PR DESCRIPTION
**Pull request by f3ew**
[d.bhagat@devdas ~]$ cat /tmp/foo.pl
my @array = qw(first second third fourth);

sub pretty_join {
  my $a = shift;

  my $string = join (', ', @$a);
  $string =~ s/(.*),/$1 &/;

  return $string;
}

my $s = pretty_join(\@array);
print "$s\n";
[d.bhagat@devdas ~]$ perl /tmp/foo.pl
first, second, third & fourth

### CODE REVIEW

**Comment by simmel** [comment]
This fails when the array is `['first', 'second', 'third', 'fourth,']` = )

**Comment by f3ew** [comment]
Updated, and fixed a bug from the older code as well :)

**Comment by simmel** [comment]
Now it strips the comma off the key, that isn't acceptable either.

Yes, the old code couldn't handle: `[1,1,"1,"]` e.g.

```perl
sub pretty_join($) {
  my ($a) = @_;
  my $str;
  for my $i (0 .. $#{$a}) {
    $str .= ' & ' if $i == $#{$a};
    $str .= @$a[$i];
    $str .= ', ' if $i < $#{$a}-1;
  }
  return $str;
}
```
is pretty clear and deals with all edge cases (that I know of).
What do you think?

**Comment by f3ew** [comment]
Meh, updated

**Comment by simmel** [comment]
```perl
use strict;
use warnings;
use Benchmark qw(:all);

sub pretty_join3 {
  my ($a) = @_;
  my $str = join(', ', @{$a}[0..$#{$a}-1]);
  $str = $str.' & '.@{$a}[$#{$a}];
  return $str;
}

sub pretty_join5 {
  my ($a) = @_;
  return join(', ', @{$a}[0..$#{$a}-1]).
  ' & '.@{$a}[$#{$a}];
}

sub pretty_join6 {
  my @a = @{$_[0]};
  return join(', ', @a[0..$#a-1]).
  ' & '.$a[$#a];
}

my @array = qw(first second third fourth);
sub main {
  timethese(3_000_000, {
    'pretty_join3' => sub { pretty_join3(\@array); },
    'pretty_join5' => sub { pretty_join5(\@array); },
    'pretty_join6' => sub { pretty_join6(\@array); },
  }
);
}
main() unless caller(0);
```

```
Benchmark: timing 3000000 iterations of pretty_join3, pretty_join5, pretty_join6...
pretty_join3:  4 wallclock secs ( 3.17 usr +  0.00 sys =  3.17 CPU) @ 946372.24/s (n=3000000)
pretty_join5:  4 wallclock secs ( 2.65 usr +  0.00 sys =  2.65 CPU) @ 1132075.47/s (n=3000000)
pretty_join6:  4 wallclock secs ( 3.54 usr +  0.00 sys =  3.54 CPU) @ 847457.63/s (n=3000000)
```

From this I learned:
* Not creating a variable is fastest
* Using an array reference instead of creating a new one is faster (even when the array only contains five elements!)

Thanks for the PR!

**Pull request closed without merging**
